---
# Hardening tasks for Nginx

- name: Disable server_tokens
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^\s*server_tokens'
    line: '    server_tokens off;'
    insertafter: 'http {'
  notify: restart nginx

- name: Set correct ownership for Nginx directories
  file:
    path: /usr/share/nginx
    owner: root
    group: root
    recurse: yes

- name: Secure nginx.conf permissions
  file:
    path: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Secure website root directory
  file:
    path: /usr/share/nginx/html
    owner: root
    group: root
    mode: '0755'

- name: Create SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Generate self-signed SSL certificate
  command: >
    openssl req -x509 -nodes -days 365
    -newkey rsa:2048
    -keyout /etc/nginx/ssl/selfsigned.key
    -out /etc/nginx/ssl/selfsigned.crt
    -subj "/C=BG/ST=Plovdiv/L=Plovdiv/O=AI-DevOps/OU=Training/CN=localhost"
  args:
    creates: /etc/nginx/ssl/selfsigned.crt
  notify: restart nginx

- name: Ensure default site configuration file exists
  copy:
    dest: /etc/nginx/conf.d/default.conf
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;

          root /usr/share/nginx/html;
          index index.html;

          server_name _;

          location / {
              try_files $uri $uri/ =404;
          }
      }
  notify: restart nginx

- name: Configure SSL in default site
  blockinfile:
    path: /etc/nginx/conf.d/default.conf
    insertafter: EOF
    block: |
      server {
          listen 443 ssl default_server;
          listen [::]:443 ssl default_server;
          ssl_certificate /etc/nginx/ssl/selfsigned.crt;
          ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

          root /usr/share/nginx/html;
          index index.html;
          server_name _;

          location / {
              try_files $uri $uri/ =404;
          }
      }
  notify: restart nginx

- name: Fix SELinux context for Nginx web root
  command: chcon -R -t httpd_sys_content_t /usr/share/nginx/html

- name: Deploy simple HTML test page
  copy:
    dest: /usr/share/nginx/html/index.html
    content: |
      <html>
      <head>
        <meta charset="UTF-8">
        <title>AI + DevOps Project</title>
        <style>
          body { text-align:center; margin-top:15%; font-family: Arial, sans-serif; }
          h1 { font-size: 28px; color: #222; }
          p { color: #555; }
        </style>
      </head>
      <body>
        <h1>Nginx is running on AWS EC2 (Amazon Linux 2023)</h1>
        <p>This page is automatically deployed via Ansible + Terraform.</p>
      </body>
      </html>
    owner: root
    group: root
    mode: '0644'

- name: Ensure correct root path in Nginx conf.d files
  replace:
    path: "/etc/nginx/conf.d/default.conf"
    regexp: "/var/www/html"
    replace: "/usr/share/nginx/html"
  notify: restart nginx

